steps:
  # 1. Compilar imagen de Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/repo-dev/app:$SHORT_SHA', '.']
  
  # 2. Subir el contenedor a Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/repo-dev/app:$SHORT_SHA']
  
  # 3. Desplegar pasando el archivo app-dev.yaml como primer argumento
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'app'
      - 'deploy'
      - 'app-dev.yaml'
      - '--image-url=us-central1-docker.pkg.dev/$PROJECT_ID/repo-dev/app:$SHORT_SHA'
      - '--quiet'

options:
  logging: CLOUD_LOGGING_ONLY
